#!/bin/bash

pass_name=$(dmenu_pass | dmenu "$@")

[[ -n $pass_name ]] && {
  pass show "$pass_name" |
  tr -d '\n' |                            # Remove last new line
  xdotool type --clearmodifiers --file -  # Send keystrokes to current window
}
