# -*- mode: ruby -*-

Vagrant.configure("2") do |config|
  config.vm.box = "generic/arch"
  config.vm.hostname = "cheese"

  config.vm.define "archlinux-cheese"
  config.vm.synced_folder "../..", "/vagrant/pkg", type: "rsync"

  config.vm.provision "shell", inline: <<-SHELL
    pacman -Sy --noconfirm binutils
  SHELL

  config.vm.provider "virtualbox" do |v|
    v.cpus = 2
    v.memory = 1024
    v.name = "archlinux-cheese"
  end
end

# vim: set ft=ruby :
